In [1]:
import pandas as pd
import datetime as dt
now = dt.datetime.now()
print(now)
print('\n*****\n')

2021-11-03 16:43:36.468348

*****

In [2]:
dr = pd.date_range(now,freq='Y',periods=5)

print(dr)

DatetimeIndex(['2021-12-31 16:43:36.468348', '2022-12-31 16:43:36.468348',
               '2023-12-31 16:43:36.468348', '2024-12-31 16:43:36.468348',
               '2025-12-31 16:43:36.468348'],
              dtype='datetime64[ns]', freq='A-DEC')

In [3]:
future = now + dt.timedelta(100)

dr = pd.date_range(now,future,freq='w')

print(dr)

DatetimeIndex(['2021-11-07 16:43:36.468348', '2021-11-14 16:43:36.468348',
               '2021-11-21 16:43:36.468348', '2021-11-28 16:43:36.468348',
               '2021-12-05 16:43:36.468348', '2021-12-12 16:43:36.468348',
               '2021-12-19 16:43:36.468348', '2021-12-26 16:43:36.468348',
               '2022-01-02 16:43:36.468348', '2022-01-09 16:43:36.468348',
               '2022-01-16 16:43:36.468348', '2022-01-23 16:43:36.468348',
               '2022-01-30 16:43:36.468348', '2022-02-06 16:43:36.468348'],
              dtype='datetime64[ns]', freq='W-SUN')

In [5]:
df = pd.DataFrame(dr,columns=['dtg'])

df['date'] = df['dtg'].dt.date

df['time'] = df.dtg.dt.time

df['month'] = df.dtg.dt.to_period('M')

df['year'] = df.dtg.dt.to_period('Y')

df

                          dtg        date             time    month  year
0  2021-08-08 20:35:18.689520  2021-08-08  20:35:18.689520  2021-08  2021
1  2021-08-15 20:35:18.689520  2021-08-15  20:35:18.689520  2021-08  2021
2  2021-08-22 20:35:18.689520  2021-08-22  20:35:18.689520  2021-08  2021
3  2021-08-29 20:35:18.689520  2021-08-29  20:35:18.689520  2021-08  2021
4  2021-09-05 20:35:18.689520  2021-09-05  20:35:18.689520  2021-09  2021
5  2021-09-12 20:35:18.689520  2021-09-12  20:35:18.689520  2021-09  2021
6  2021-09-19 20:35:18.689520  2021-09-19  20:35:18.689520  2021-09  2021
7  2021-09-26 20:35:18.689520  2021-09-26  20:35:18.689520  2021-09  2021
8  2021-10-03 20:35:18.689520  2021-10-03  20:35:18.689520  2021-10  2021
9  2021-10-10 20:35:18.689520  2021-10-10  20:35:18.689520  2021-10  2021
10 2021-10-17 20:35:18.689520  2021-10-17  20:35:18.689520  2021-10  2021
11 2021-10-24 20:35:18.689520  2021-10-24  20:35:18.689520  2021-10  2021
12 2021-10-31 20:35:18.689520  2021-10-31  20:35:18.689520  2021-10  2021
13 2021-11-07 20:35:18.689520  2021-11-07  20:35:18.689520  2021-11  2021

In [6]:
df['dtg_str'] = df.dtg.astype(str)

df['dtg2'] = pd.to_datetime(df.dtg_str)



df['dtg_str_cust'] = '2021ff03ff01'

df['dtg_str_frmt']=pd.to_datetime(df.dtg_str_cust,format="%Yff%mff%d",errors='coerce')



df

,dtg,date,time,month,year,dtg_str,dtg2,dtg_str_cust,dtg_str_frmt
0,2021-08-08 20:35:18.689520,2021-08-08,20:35:18.689520,2021-08,2021,2021-08-08 20:35:18.689520,2021-08-08 20:35:18.689520,2021ff03ff01,2021-03-01
1,2021-08-15 20:35:18.689520,2021-08-15,20:35:18.689520,2021-08,2021,2021-08-15 20:35:18.689520,2021-08-15 20:35:18.689520,2021ff03ff01,2021-03-01
2,2021-08-22 20:35:18.689520,2021-08-22,20:35:18.689520,2021-08,2021,2021-08-22 20:35:18.689520,2021-08-22 20:35:18.689520,2021ff03ff01,2021-03-01
3,2021-08-29 20:35:18.689520,2021-08-29,20:35:18.689520,2021-08,2021,2021-08-29 20:35:18.689520,2021-08-29 20:35:18.689520,2021ff03ff01,2021-03-01
4,2021-09-05 20:35:18.689520,2021-09-05,20:35:18.689520,2021-09,2021,2021-09-05 20:35:18.689520,2021-09-05 20:35:18.689520,2021ff03ff01,2021-03-01
5,2021-09-12 20:35:18.689520,2021-09-12,20:35:18.689520,2021-09,2021,2021-09-12 20:35:18.689520,2021-09-12 20:35:18.689520,2021ff03ff01,2021-03-01
6,2021-09-19 20:35:18.689520,2021-09-19,20:35:18.689520,2021-09,2021,2021-09-19 20:35:18.689520,2021-09-19 20:35:18.689520,2021ff03ff01,2021-03-01
7,2021-09-26 20:35:18.689520,2021-09-26,20:35:18.689520,2021-09,2021,2021-09-26 20:35:18.689520,2021-09-26 20:35:18.689520,2021ff03ff01,2021-03-01
8,2021-10-03 20:35:18.689520,2021-10-03,20:35:18.689520,2021-10,2021,2021-10-03 20:35:18.689520,2021-10-03 20:35:18.689520,2021ff03ff01,2021-03-01
9,2021-10-10 20:35:18.689520,2021-10-10,20:35:18.689520,2021-10,2021,2021-10-10 20:35:18.689520,2021-10-10 20:35:18.689520,2021ff03ff01,2021-03-01
10,2021-10-17 20:35:18.689520,2021-10-17,20:35:18.689520,2021-10,2021,2021-10-17 20:35:18.689520,2021-10-17 20:35:18.689520,2021ff03ff01,2021-03-01
11,2021-10-24 20:35:18.689520,2021-10-24,20:35:18.689520,2021-10,2021,2021-10-24 20:35:18.689520,2021-10-24 20:35:18.689520,2021ff03ff01,2021-03-01
12,2021-10-31 20:35:18.689520,2021-10-31,20:35:18.689520,2021-10,2021,2021-10-31 20:35:18.689520,2021-10-31 20:35:18.689520,2021ff03ff01,2021-03-01
13,2021-11-07 20:35:18.689520,2021-11-07,20:35:18.689520,2021-11,2021,2021-11-07 20:35:18.689520,2021-11-07 20:35:18.689520,2021ff03ff01,2021-03-01